name: Unit-tests on Linux CPU

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*
  workflow_dispatch:

env:
  CHANNEL: "nightly"

jobs:
  tests:
    strategy:
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10"]
      fail-fast: false
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: linux.12xlarge
      repository: pytorch/rl
      script: |
        # Mark Build Directory Safe
        git config --global --add safe.directory /__w/rl/rl

        # Set up Environment Variables
        export PYTHON_VERSION="${{ matrix.python_version }}"
        export VERSION="cpu"
        export CUDATOOLKIT="cpuonly"
        export MUJOCO_GL="osmesa"

        # Set CHANNEL
        if [[ (${GITHUB_EVENT_NAME} = 'pull_request' && (${GITHUB_BASE_REF} = 'release'*)) || (${GITHUB_REF} = 'refs/heads/release'*) ]]; then
          export CHANNEL=test
        else
          export CHANNEL=nightly
        fi

        # Create Conda Env
        conda create -yp ci_env python="${PYTHON_VERSION}" numpy libpng jpeg scipy
        conda activate /work/ci_env
        
        # Install PyTorch, TorchRL, and testing libraries
        set -ex
        pip3 install \
            --pre torch torchvision torchaudio \
            --extra-index-url https://download.pytorch.org/whl/nightly/cpu
        # smoke test
        python -c "import functorch"

        # install snapshot
        pip install git+https://github.com/pytorch/torchsnapshot

        # install tensordict
        pip install git+https://github.com/pytorch-labs/tensordict.git
        python3 setup.py develop
        
        #python3 -m pip install pytest pytest-mock 'av<10'

        # Run Tests
        python3 -m torch.utils.collect_env
        python3 -m pytest --junitxml=test-results/junit.xml -v --durations 20
